# Generated by Django 4.0.1 on 2022-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('BOM TRAMA', 'trama'), ('AÇÃO', 'ação'), ('OUTROS', 'outros')], max_length=15),
        ),
    ]
