# Generated by Django 4.0.1 on 2022-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_alter_filme_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='thumb_ep',
            field=models.ImageField(default='SOME STRING', upload_to='thumb_episodios'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('BOM TRAMA', 'trama'), ('AÇÃO', 'ação'), ('OUTROS', 'outros'), ('TERROR', 'terror'), ('FPS', 'FPS')], max_length=15),
        ),
    ]
