# Generated by Django 4.0.1 on 2022-02-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_episodio_thumb_ep_alter_filme_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='thumb_ep',
            new_name='thumb',
        ),
    ]
